### ISSUE TITLE
Unable to reproduce CRAN issue

### ISSUE THREAD

**Issue by privefl** [rocker-org/r-devel-san-clang#13]
Dear Dirk,

I've come across your post http://r.789695.n4.nabble.com/Request-for-help-with-UBSAN-and-total-absense-of-CRAN-response-td4701735.html.
I have a similar problem. My package {bigstatsr} has clang-UBSAN  issues.
I've tried to reproduce this issue with docker image `rocker/r-devel-ubsan-clang`.

My process has been:
1. Download the repo in `/opt/bigstatsr` and go to the specific commit 
```
git clone https://github.com/privefl/bigstatsr.git
git checkout 732f78c1604caa1106296a14af24e199038f55fd
```
2. Install all dependencies
```
install.packages(c("bigreadr", "cowplot", "doParallel", "ggplot2", "Rcpp",
                   "RSpectra", "tibble", "RcppArmadillo", "rmio", "bigalgebra",
                   "biglasso", "bigmemory", "covr", "glmnet", "microbenchmark",
                   "ModelMetrics", "RhpcBLASctl", "spelling", "testthat"))
install.packages("devtools"); devtools::install_github("privefl/bigreadr@e17b839dd4e3eba967c40c14822be80fb45cdddc")
```
3. Build the package and check it.

But no issue..
Do you have any input on this please?

**Comment by eddelbuettel** [comment]
I do not. I had a UBSAN issue to fix, it did not reproduce with the nice and comprehensive `r-devel` container by @wch so I updated this one -- following BDR's setup.  Worked for me this time, but this is somewhat trial and error.  I suggest you clone and try that locally.  I really wish CRAN offered theirs as containers but they don't -- so _c'est la vie_.

**Comment by franzbischoff** [comment]
My 2 cents:

I also have an issue with USBAN on CRAN. Surprisingly I received a reply when asking how to reproduce the error without their submission system.

The answer was: "Yes, see https://www.stats.ox.ac.uk/pub/bdr/memtests/README.txt"

Well, I've already tried to use the rockers available here but I could not figure out how to reproduce the same error they had:

```
> mp <- stamp(motifs_discords_small, 50)
/data/gannet/ripley/R/test-clang/Rcpp/include/Rcpp/internal/caster.h:30:25: runtime error: -inf is outside the range of representable values of type 'int'
    #0 0x7f5e6f50c6bd in void Rcpp::Vector<13, Rcpp::PreserveStorage>::fill__dispatch<double>(Rcpp::traits::integral_constant<bool, true>, double const&) (/data/gannet/ripley/R/packages/tests-clang-SAN/matrixprofiler.Rcheck/matrixprofiler/libs/matrixprofiler.so+0x1fa6bd)
    #1 0x7f5e6f55221c in Rcpp::Vector<13, Rcpp::PreserveStorage>::Vector<unsigned long, double>(unsigned long const&, double const&, Rcpp::traits::enable_if<traits::is_arithmetic<unsigned long>::value, void>::type*) (/data/gannet/ripley/R/packages/tests-clang-SAN/matrixprofiler.Rcheck/matrixprofiler/libs/matrixprofiler.so+0x24021c)
    #2 0x7f5e6f5498a5 in stamp_rcpp(Rcpp::Vector<14, Rcpp::PreserveStorage>, Rcpp::Vector<14, Rcpp::PreserveStorage>, unsigned int, double, bool) (/data/gannet/ripley/R/packages/tests-clang-SAN/matrixprofiler.Rcheck/matrixprofiler/libs/matrixprofiler.so+0x2378a5)
(...)
```

Well, I'm using WSL for Linux testing, with ubuntu 20.04, so I tried myself and after this configuration I got there:

1) install clang and whatever is needed to compile your package
2) I opened my package project and used devtools::build() to create the .tar.gz file
3) I opened a vanilla session and installed all suggested, imports and whatever was needed to build/test/check my package
4) Only now we begin to care about the ASAN/USBAN. Create a file ~/.R/Makevars
5) Add these content there (I had to change CXX to CXX11 because of my project, you need to figure out if the check is done with clang:
`CC= clang -fsanitize=address,undefined -fno-sanitize=float-divide-by-zero -fno-sanitize=alignment -fno-omit-frame-pointer
CXX11= clang++ -fsanitize=address,undefined -fno-sanitize=float-divide-by-zero -fno-sanitize=alignment -fno-omit-frame-pointer -frtti
CFLAGS= -g -O3 -Wall -pedantic
FFLAGS= -g -O2 -mtune=native
CXXFLAGS= -g -O3 -Wall -pedantic
MAIN_LD= clang++ -fsanitize=undefined,address
PKG_LIBS = -lasan -lubsan`

check your package with this command:

`LD_PRELOAD=/usr/lib/gcc/x86_64-linux-gnu/9/libasan.so ASAN_OPTIONS='detect_leaks=0:detect_odr_violation=0' R CMD check mypackage_0.1.2.tar.gz`

6) the errors will probably be on some .out .Rout file inside the mypackage.Rcheck folder that is created by the check

PS.:
- `PKG_LIBS -lasan -lubsan` was needed because a linker complain
- The command line need to start with `LD_PRELOAD` because I didn't figure out how to load libasan.so other way. ASAN_OPTIONS will disable those two checks, seems not to be important in our context somehow...

Happy coding.
